"""Phase 9: export model-derived parameters for the front end.

Writes ``user_ui/data/model_params.js`` as a ``window.F1_MODEL`` assignment.

It must be a ``.js`` assignment rather than a ``.json`` file: ``user_ui`` is
opened directly from ``file://``, where ``fetch('data/model_params.json')`` is
blocked by CORS and fails silently. A ``<script>`` tag carries no such
restriction.

The export replaces the hardcoded ``COMPOUND_DATA`` and ``CIRCUITS`` constants
in ``app.js``, which the file itself describes as "a synthetic model for
demonstration". Every entry carries its provenance, so the page can show which
numbers rest on observed stints and which are model estimates.

    .venv\\Scripts\\python.exe scripts/run_export_ui.py
"""
from __future__ import annotations

import json
import sys
from datetime import datetime, timezone
from pathlib import Path

import pandas as pd

PROJECT_ROOT = Path(__file__).resolve().parent.parent
if str(PROJECT_ROOT) not in sys.path:
    sys.path.insert(0, str(PROJECT_ROOT))

from src import config                                  # noqa: E402
from src.core.pipeline import F1Pipeline                # noqa: E402
from src.simulation import strategy as strat            # noqa: E402

UI_DIR = PROJECT_ROOT.parent / "user_ui"


def main() -> int:
    """Build and write the front-end parameter file."""
    logger = config.setup_logging("export_ui")

    pipeline = F1Pipeline().load()
    ui_map = config.ui_circuit_map()
    pace = pipeline.reference["pace"]

    circuits: dict[str, dict] = {}
    for slug, entry in ui_map["circuits"].items():
        event_name = entry["event_name"]
        row = pace[pace["EventName"] == event_name]
        if row.empty:
            logger.warning("No collected data for %s (%s); skipping", slug, event_name)
            continue

        params = {"circuit": slug, "conditions": "dry",
                  "compounds": list(strat.DRY_COMPOUNDS)}
        deg_table, _ = pipeline._degradation_table(event_name, list(strat.DRY_COMPOUNDS),
                                                   params, [])
        circuits[slug] = {
            "name": entry["ui_label"],
            "event": event_name,
            "laps": int(row["race_laps"].iloc[0]),
            "baseLap": round(float(row["base_lap_s"].iloc[0]), 3),
            "compounds": {
                compound: {
                    "degRate": round(value["deg_rate"], 5),
                    "q25": round(value["q25"], 5),
                    "q75": round(value["q75"], 5),
                    "nStints": int(value["n_stints"]),
                    "source": value["source"],
                }
                for compound, value in deg_table.items()
            },
        }
        logger.info("  %-12s %-26s %2d laps, base %.2f s, sources %s",
                    slug, event_name, circuits[slug]["laps"],
                    circuits[slug]["baseLap"],
                    {c: v["source"][:3] for c, v in deg_table.items()})

    metrics = pipeline.metrics or {}
    payload = {
        "circuits": circuits,
        "compoundOrder": list(strat.DRY_COMPOUNDS),
        "paceOffset": strat.DEFAULT_PACE_OFFSET,
        "pitLossS": pipeline.config["strategy"]["pit_loss_s"],
        "fuel": {
            "penaltySPerKg": pipeline.config["fuel_correction"]["penalty_s_per_kg"],
            "initialKg": pipeline.config["fuel_correction"]["initial_fuel_kg"],
        },
        "meta": {
            "generated": datetime.now(timezone.utc).isoformat(timespec="seconds"),
            "trainSeasons": metrics.get("train_seasons"),
            "holdoutSeason": metrics.get("holdout_season"),
            "nStints": pipeline.reference["n_stints"],
            "holdoutMAE": (metrics.get("metrics", {})
                           .get("xgboost", {}).get("MAE")),
            "holdoutR2": (metrics.get("metrics", {})
                          .get("xgboost", {}).get("R2")),
            "oracleCeilingPct": metrics.get("oracle_ceiling_pct"),
            "shareOfHeadroomPct": metrics.get("share_of_headroom_pct"),
            "gate4Pass": metrics.get("gate4_pass"),
            "units": "degRate is seconds of lap time lost per lap of tyre age",
            "caveat": ("Degradation is linear in tyre age; the non-linear cliff "
                       "beyond a tyre's working range is not modelled. Dry "
                       "running only, 2022-2024 regulation era."),
        },
    }

    out_dir = UI_DIR / "data"
    out_dir.mkdir(parents=True, exist_ok=True)
    out_path = out_dir / "model_params.js"

    body = json.dumps(payload, indent=2)
    out_path.write_text(
        "/* Generated by scripts/run_export_ui.py - do not edit by hand.\n"
        "   Emitted as a .js assignment rather than .json because user_ui is\n"
        "   opened from file://, where fetch() is blocked by CORS. */\n"
        f"window.F1_MODEL = {body};\n", encoding="utf-8")

    logger.info("Wrote %s (%d circuits, %.1f KB)",
                out_path, len(circuits), out_path.stat().st_size / 1024)
    observed = sum(1 for c in circuits.values()
                   for v in c["compounds"].values() if v["source"] == "observed")
    total = sum(len(c["compounds"]) for c in circuits.values())
    logger.info("Provenance: %d of %d circuit-compound pairs rest on observed "
                "stints; the rest are model estimates", observed, total)
    return 0


if __name__ == "__main__":
    sys.exit(main())
